name: EnoughSkyblock
version: '${project.version}'
main: io.github.enoughskyblock.EnoughSkyblock
api-version: 1.16
commands:
  aic:
    description: Skyblock Admin Item Browser GUI
    aliases: ib
    permission: skyblock.aic
    permission-message: Sorry you cannot do this!
  deliverhelm:
    description: WIP
    aliases: dhelm
    permission: skyblock.deliver
    permission-message: Sorry you cannot do this!
  deliverkloonboat:
    description: WIP
    aliases: dboat
    permission: skyblock.deliver
    permission-message: Sorry you cannot do this!
  deliverbuilderclay:
    description: WIP
    aliases: dclay
    permission: skyblock.deliver
    permission-message: Sorry you cannot do this!
  delivercreativemind:
    description: WIP
    aliases: dmind
    permission: skyblock.deliver
    permission-message: Sorry you cannot do this!
